load("//build/rules/yarn/defs.bzl", "js_module")

js_module(
    name = "app",
    srcs = ["index.js"],
    entry = "index.js",
    deps = [
        "//third-party/node:react-dom-19.0.0",
        "//third-party/node:react-19.0.0",
        "//third-party/node:react-router-7.2.0",
    ],
    visibility = ["PUBLIC"],
)
