load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")
load("@root//rules/typescript:defs.bzl", "typescript_toolchain")

# All the default toolchains, suitable for a quick demo or early prototyping.
# Most real projects should copy/paste the implementation to configure them.
system_demo_toolchains()

typescript_toolchain(
    name = "typescript",
    visibility = ["PUBLIC"],
)
