rust_binary(
    name = "backend",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//third-party/rust:tokio",
        "//third-party/rust:tower-http",
        "//third-party/rust:axum",
        "//common/resources:buck_resources",
    ],
    resources = {
        "javascript_assets": "//frontend:app",
    },
)
