rust_binary(
    name = "backend",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//third-party/rust:tokio",
        "//third-party/rust:tower-http",
        "//third-party/rust:axum",
        "//build/utils/buck-resources:buck-resources",
    ],
    resources = {
        "bundle.js": "//frontend:app",
        "index.html": ":index.html",
    },
)

export_file(
    name = "index.html",
    src = "assets/index.html",
)
