[workspace]

[package]
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

[[bin]]
name = "fake"
path = "."

[dependencies]
axum = "0.8.1"
dunce = "1.0.5"
serde_json = "1.0.138"
thiserror = "2.0.11"
tokio = { version = "1.43", features = ["fs", "macros", "rt-multi-thread", "io-util", "process", "signal" ] } 
tower-http = { version = "0.6.2", features = ["fs"] }
