# Helper for accessing buck2 resources
rust_library(
    name = "buck_resources",
    srcs = ["src/lib.rs"],
    deps = [
        "//third-party/rust:dunce",
        "//third-party/rust:serde_json",
        "//third-party/rust:thiserror",
    ],
    visibility = ["PUBLIC"],
)
