omit_targets = []
extra_srcs = []
omit_srcs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
omit_deps = []
cargo_env = false
linker_flags = []

[rustc_flags_select]

[env]

[[buildscript]]
unresolved = "Unresolved build script at ../../../../.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/openssl-sys-0.9.106/build/main.rs."

[extra_mapped_srcs]

[platform_fixup]
